import {StyleSheet,Dimensions} from 'react-native';
const height = Dimensions.get('window').height;
const width = Dimensions.get('window').width;
export default StyleSheet.create({
    container: {
        flexDirection: "column",
        backgroundColor:"#231F21",
        flex:1
    },  
    img:{
        height:height*0.379,
        width:'100%',
        resizeMode:'cover',    
        borderBottomLeftRadius:20,
        borderBottomRightRadius:20
    },   
    conferenceBox:{
        position:'relative',
        bottom:(height-56)*0.21/2,
        left:0,
        width:width-32,
        marginHorizontal:16,
        backgroundColor:'#2B292A',
        height:(height-56)*0.22,
        marginBottom:20,
        borderRadius:7,
    },
    conferenceContent:{ 
        padding:20,
    },
    titlearea:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:"space-between",
    },
    sestitlearea:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:"space-between",
        paddingHorizontal:20,
    },
    date:{
        color:"#F35174",
        fontSize:12
    },
    title:{
        color:'white',
        fontSize:18,
        fontWeight:'bold',
        marginBottom:5
    },
    more:{
        backgroundColor:"#F36180",
        paddingHorizontal:17,
        paddingVertical:3,
        borderRadius:12
    },
    moretxt:{
        color:'white'
    },
    confcontent:{
        color:'white',
        fontSize:14,
        marginBottom:30,
        lineHeight:20,
        width:'80%',
    },
    content:{
        color:'white',
        fontSize:14,
        marginBottom:30,
        lineHeight:20,
    },
    sessionlist:{
        display:'flex',
        flexDirection:'column',
        paddingHorizontal:16
    },
    sessionbox:{
        flexDirection:'row',
        paddingHorizontal:16,
        marginBottom:20,
    },
    sessiontxt:{
        color:'white',
        fontSize:16,        
        marginRight:10
    },
    sessioncnt:{
        color:"#F35174",
        fontSize:18,
    },
    sessionwrap:{
        marginBottom:10,
        bottom:(height-56)*0.21/2,
    },
    sessioneContent:{
        width:width*0.922,
        paddingVertical:25,
        borderRadius:7,
        marginBottom:10,
        backgroundColor:'#2B292A'
    },
    sessionimg:{
        width:85,   
        height:85,
        borderRadius:10
    },
    txtbox:{
        width:width*0.597,
        height:85
    },
    sessiontitle:{
        color:'white',
        fontSize:18,
        fontWeight:'bold',
        marginBottom:5
    },
    sessionimgbox:{
        flexDirection:'row'
    },
    arrowimg:{
        width:60,
        height:34,
        bottom:-55,
        right:30
    },
    list:{
        alignItems:"center"
    }
  });
  