import {StyleSheet,Dimensions} from 'react-native';
const height = Dimensions.get('window').height;
const width = Dimensions.get('window').width;
export default StyleSheet.create({
    container: {
        flex: 1,
        flexDirection: "column",
        backgroundColor:"#231F21",
    },  
    content:{
        paddingHorizontal:16,
        paddingVertical:20
    },
    image:{
        height:(height-56)*0.2
    },
    conferbox:{
        paddingHorizontal:20,
        paddingVertical:26
    },
    time:{
        color:"#F35174",
        fontSize:14
    },
    title:{
        color:'white',
        fontSize:18,
        marginBottom:10
    },
    des:{
        color:'white',
        fontSize:13
    },
    sessionheader:{
        height:50,
        flexDirection:'row',
        borderBottomWidth:1,
        borderBottomColor:'#A1A1A11A'
    },
    tabbtn:{
        width:width/2,
        justifyContent:'space-between',
        alignItems:'center'
    },
    tabtext:{
        color:'#AAAAAA',
        fontSize:16
    },
    tabactivetext:{
        color:'#F35174',
        fontSize:16
    },
    activetab:{
        width:(width/2)*0.34,
        justifyContent:'center',
        alignItems:'center',
        borderBottomColor:'#F35174',
        borderBottomWidth:2
    },
    seslistwrap:{
        paddingHorizontal:16,
        borderBottomWidth:1,
        borderBottomColor:'#A1A1A11A'
    },
    seslist:{
        paddingHorizontal:10,
        paddingVertical:26,
        flexDirection:'row',
        justifyContent:'space-between',

    },
    lang:{
        color:"white",
        fontSize:14,
        fontWeight:'700',
        marginRight:11
    },
    sesplay:{
        width:25,
        height:25,
    },
    seseq:{
        width:20,
        height:20,
        marginRight:5
    },
    soundbox:{
        flex:1,
        paddingHorizontal:16,
        marginVertical:20,
        flexDirection:'row',
        alignItems:'flex-end'
    },
    soundimg:{
        width:20,
        height:16,
        resizeMode:'cover',
        marginRight:8,
    },
    soundView:{
        width:width-18-48,
        height:14,
        flexDirection:'row',

    },
    bar:{
        width:2,
        marginRight:2,
        backgroundColor:"#AAAAAA"
    },
    activebar:{
        width:2,
        marginRight:2,
        backgroundColor:"#F35174"
    },
    databox:{
        flexDirection:"row",
    },
    volume:{
        color:'#AAAAAA',
        fontSize:13,
    },
    round:{
        width:6,
        height:6,
        borderRadius:6,
        marginRight:5,
        backgroundColor:'#ffffff'
    },
    soundAnddurationbox:{
        justifyContent:'flex-end',
        flex:1
    },
    durationbox:{
        flexDirection:'row',
        justifyContent:'flex-end',
        alignItems:"center",
        paddingHorizontal:16,
    },
    txtmr:{
        color:'#ffffff',
        fontSize:12,
    },
    durationView:{
        width:width-18-48,
        height:14,
        flexDirection:'row',
        alignItems:"center",
        justifyContent:"flex-end",
        marginRight:8,
    },
    stopbox:{
        flexDirection:'row'
    },
    listbox:{
        height:height*0.56
    }
  });
  